import { chromium } from 'playwright-core';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
const output = process.env.BRIA_BROWSER_OUTPUT;
if (!output) throw new Error('Indica la carpeta privada de capturas.');
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } }), page = await context.newPage(), errors = [], external = [];
const base = 'http://127.0.0.1:3017', code = `BRIA-CHAT-${Date.now()}`;
let learning;
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => { if (new URL(request.url()).hostname === 'api.openai.com') external.push(request.url()); });
const newChat = async () => {
  await page.locator('header').getByRole('button', { name: 'Nueva conversación', exact: true }).click();
  await page.getByRole('heading', { name: 'Hola, Rodny', exact: true }).waitFor();
};
const ask = async text => {
  await page.getByLabel('Mensaje para Bria', { exact: true }).fill(text);
  const response = page.waitForResponse(res => /\/api\/bria\/conversations\/[^/]+\/messages$/.test(res.url()) && res.request().method() === 'POST', { timeout: 180000 });
  await page.getByRole('button', { name: 'Enviar mensaje', exact: true }).click();
  const returned = await response;
  assert.equal(returned.status(), 200, await returned.text());
  const chat = await returned.json();
  await page.locator('[data-conversation-turn="assistant"]').last().waitFor();
  await page.waitForFunction(() => !document.querySelector('button[aria-label="Nueva conversación"]')?.disabled);
  return chat;
};
try {
  await page.goto(base);
  await page.getByLabel('Mensaje para Bria').waitFor();
  await newChat();
  const reviewed = await ask('PRUEBA DE REVISIÓN: Revisa las 12 piezas de la parrilla de Aristea de octubre de 2026 en la plataforma. Dame cuatro observaciones concretas y tres pasos para empezar; no uses parrillas históricas como si fueran esta.');
  const answer = reviewed.turns.at(-1);
  assert.match(answer.text, /Aristea|octubre/i);
  assert.ok(answer.toolsUsed.includes('parrilla_de_cliente'));
  assert.ok(answer.toolsUsed.includes('leer_piezas_de_parrilla'));
  assert.equal(answer.sources.filter(source => source.kind === 'pieza').length, 12);
  await page.screenshot({ path: path.join(output, 'bria-panel-aristea.jpg'), type: 'jpeg', quality: 85 });
  await page.getByRole('link', { name: 'Clientes', exact: true }).first().click();
  assert.equal(await page.locator('[data-bria-assistant-panel]').isVisible(), true);
  assert.match(await page.locator('[data-conversation-turn="assistant"]').last().innerText(), /Aristea|octubre/i);
  await page.getByRole('button', { name: 'Cerrar Bria', exact: true }).click();
  assert.equal(await page.locator('[data-bria-assistant-panel]').isVisible(), false);
  await page.getByRole('button', { name: 'Preguntarle a Bria', exact: true }).click();
  assert.match(await page.locator('[data-conversation-turn="assistant"]').last().innerText(), /Aristea|octubre/i);
  await page.reload();
  await page.locator('[data-conversation-turn="assistant"]').last().waitFor();
  assert.match(await page.locator('[data-conversation-turn="assistant"]').last().innerText(), /Aristea|octubre/i);
  await page.getByRole('button', { name: 'Pantalla completa', exact: true }).click();
  assert.equal(await page.locator('[data-bria-assistant-panel]').getAttribute('data-bria-mode'), 'fullscreen');
  assert.equal(await page.getByLabel('Historial de conversaciones').isVisible(), true);
  await page.screenshot({ path: path.join(output, 'bria-pantalla-completa.jpg'), type: 'jpeg', quality: 85 });
  await page.getByRole('button', { name: 'Volver al panel lateral', exact: true }).click();
  await newChat();
  await ask(`PRUEBA PERSONAL: Recuerda, solo para mí y como ejemplo ficticio de prueba, que el código de esta demostración es ${code}. No aplica a clientes ni al negocio real.`);
  const records = await context.request.get(`${base}/api/bria/knowledge`);
  learning = (await records.json()).find(row => row.status === 'ACTIVE' && row.text.includes(code));
  assert.ok(learning); assert.equal(learning.scope, 'PERSONAL');
  await newChat();
  const recalled = await ask('PRUEBA PERSONAL: ¿Qué código de demostración te pedí recordar? Consulta tu memoria.');
  assert.match(recalled.turns.at(-1).text, new RegExp(code));
  assert.ok(recalled.turns.at(-1).sources.some(source => source.kind === 'aprendizaje' && source.id === learning.id));
  await page.getByRole('button', { name: 'Menú de Bria' }).click();
  await page.getByRole('menuitem', { name: 'Registro', exact: true }).click();
  await page.getByText(learning.text, { exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Enseñar a Bria' }).count(), 0);
  assert.equal(await page.getByLabel('Tema del aprendizaje').count(), 0);
  await page.getByRole('button', { name: 'Volver a la conversación' }).click();
  await page.getByRole('button', { name: 'Menú de Bria' }).click();
  await page.getByRole('menuitem', { name: 'Historial', exact: true }).click();
  await page.getByRole('button', { name: /^PRUEBA DE REVISIÓN:/ }).first().click();
  await page.getByRole('button', { name: 'Modo oscuro', exact: true }).click();
  await page.screenshot({ path: path.join(output, 'bria-panel-oscuro.jpg'), type: 'jpeg', quality: 85 });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.screenshot({ path: path.join(output, 'bria-panel-movil.jpg'), type: 'jpeg', quality: 85 });
  await page.route('**/api/bria/conversations/*/messages', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ message: 'Conexión no disponible temporalmente.' }) }));
  await page.getByLabel('Mensaje para Bria').fill('Pregunta conservada al fallar');
  await page.getByRole('button', { name: 'Enviar mensaje' }).click();
  await page.getByRole('alert').waitFor();
  assert.equal(await page.getByLabel('Mensaje para Bria').inputValue(), 'Pregunta conservada al fallar');
  assert.deepEqual(errors, []); assert.deepEqual(external, []);
  const report = { passed: true, actualPlatformPlan: 'Aristea / octubre 2026 / 12 piezas', realModelRequests: 3, browserExternalRequests: 0, checks: ['Live platform copy read and reviewed', 'Dock survives module navigation and source links', 'Closing and reopening preserves chat', 'PostgreSQL chat history survives reload', 'Full screen shows history', 'Natural personal teaching is saved without a form', 'New conversation recalls the persisted teaching', 'Read-only memory log and withdrawal', 'Dark and mobile without horizontal overflow', 'Failed message returns to composer'], pageErrors: errors };
  await writeFile(path.join(output, 'bria-conversation-verification.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report));
} finally {
  if (learning) await context.request.post(`${base}/api/bria/knowledge/${learning.id}/revoke`, { data: { expectedRevision: learning.revision } });
  await browser.close();
}
