import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
const base = 'http://127.0.0.1:3002';
const initial = await fetch(`${base}/api/demo`).then(response => { assert.equal(response.status, 200); return response.json(); });
assert.ok(initial.viewers.includes('Responsable') && initial.review.summary.includes('ficticias'));
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1366, height: 1000 }, reducedMotion: 'reduce' }); page.setDefaultTimeout(8000);
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${base}/tests/fixtures/bria-pilot.html`);
  await page.getByLabel('Probar como').selectOption('Colaborador');
  await page.getByRole('button', { name: 'Criterios del cliente', exact: true }).click();
  let dialog = page.getByRole('dialog');
  await dialog.getByText('Usar un tono cercano y tratar a la audiencia de tú.').waitFor();
  assert.equal(await dialog.getByRole('button', { name: 'Aprobar', exact: true }).count(), 0);
  const stored = await fetch(`${base}/api/content/plans/${initial.planId}/criteria`).then(response => response.json());
  const criterion = stored.criteria.find(item => item.status === 'PROPOSED');
  assert.ok(criterion);
  const denied = await fetch(`${base}/api/content/plans/${initial.planId}/criteria/${criterion.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'APPROVE', version: criterion.version, reason: 'Intento de prueba sin permiso', role: 'ADMIN' }) });
  assert.equal(denied.status, 403);
  await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'hidden' });
  await page.getByLabel('Probar como').selectOption('Responsable');
  await page.getByRole('button', { name: 'Criterios del cliente', exact: true }).click();
  await dialog.getByRole('button', { name: 'Aprobar', exact: true }).click();
  await dialog.getByLabel('Motivo de la decisión').fill('Prueba de aprobación persistida en PostgreSQL local.');
  await dialog.getByRole('button', { name: 'Confirmar aprobación', exact: true }).click();
  await dialog.getByText('Aprobado', { exact: true }).waitFor();
  await page.reload();
  await page.getByRole('button', { name: 'Criterios del cliente', exact: true }).click();
  await dialog.getByText('Aprobado', { exact: true }).waitFor();
  await dialog.getByRole('button', { name: 'Historial', exact: true }).click();
  await dialog.getByText('Prueba de aprobación persistida en PostgreSQL local.').waitFor();
  await page.evaluate(() => document.fonts.ready);
  await page.waitForFunction(() => Number(getComputedStyle(document.querySelector('[role=dialog]')).opacity) === 1);
  await page.screenshot({ path: 'output/bria-pilot-persisted-desktop.png', fullPage: true });
  await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Detalle del puntaje' }).click();
  await dialog.getByText('Alcance parcial', { exact: true }).waitFor();
  await page.waitForFunction(() => Number(getComputedStyle(document.querySelector('[role=dialog]')).opacity) === 1);
  await page.screenshot({ path: 'output/bria-pilot-score-desktop.png', fullPage: true });
  await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'hidden' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Criterios del cliente', exact: true }).click();
  await dialog.getByText('Aprobado', { exact: true }).waitFor();
  await page.waitForFunction(() => Number(getComputedStyle(document.querySelector('[role=dialog]')).opacity) === 1);
  await page.screenshot({ path: 'output/bria-pilot-persisted-mobile.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  assert.deepEqual(errors, []);
  console.log('Real local backend: unauthorized role rejected, owner approval persisted after reload, history and responsive score UI OK.');
} finally { await browser.close(); }
