import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright-core';
import { createBriaPreview } from '../../scripts/preview-bria.js';
const output = process.env.SCREENSHOT_DIR || 'output/bria-deletion';
await mkdir(output, { recursive: true });
const preview = await createBriaPreview({ port: 3735 });
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = []; page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto(`${preview.origin}/?abierta&role=admin`);
  const panel = page.getByRole('region', { name: 'Conversación con Bria' });
  const ready = () => page.waitForFunction(() => !document.querySelector('[aria-label="Nueva conversación"]')?.disabled);
  await panel.waitFor(); await ready();
  const input = page.getByLabel('Mensaje para Bria');
  await input.fill('Revisa la parrilla de Endova'); await input.press('Enter'); await ready();
  await page.getByRole('button', { name: 'Pantalla completa' }).click();
  const remove = page.getByRole('button', { name: 'Borrar conversación: Revisa la parrilla de Endova' });
  await remove.click({ timeout: 10000 });
  const dialog = page.getByRole('alertdialog');
  await dialog.waitFor(); assert.match(await dialog.textContent(), /Lo que Bria aprendió se conserva/);
  await page.screenshot({ path: path.join(output, 'bria-borrar-claro.png') });
  await page.getByRole('button', { name: 'Cancelar', exact: true }).click();
  assert.equal(await remove.count(), 1); assert.equal(await page.locator('[data-conversation-turn]').count(), 2);
  await panel.locator('button[aria-label="Nueva conversación"]').click(); await ready();
  await input.fill('Qué tengo pendiente'); await input.press('Enter'); await ready();
  await input.fill('Borrador que debe conservarse');
  await page.getByLabel('Archivos para Bria').setInputFiles({ name: 'pendiente.txt', mimeType: 'text/plain', buffer: Buffer.from('Archivo ficticio por enviar.') });
  const failDeletion = async route => route.request().method() === 'DELETE' ? route.fulfill({ status: 503, json: { message: 'No se pudo borrar ahora.' } }) : route.continue();
  await page.route('**/api/bria/conversations/*', failDeletion);
  await remove.click(); await page.getByRole('button', { name: 'Borrar definitivamente', exact: true }).click();
  await panel.getByRole('alert').waitFor();
  assert.equal(await remove.count(), 1); assert.equal(await input.inputValue(), 'Borrador que debe conservarse');
  await page.unroute('**/api/bria/conversations/*', failDeletion);
  await page.evaluate(() => document.documentElement.classList.add('dark'));
  await remove.click(); await dialog.waitFor();
  await page.screenshot({ path: path.join(output, 'bria-borrar-oscuro.png') });
  await page.getByRole('button', { name: 'Borrar definitivamente', exact: true }).click();
  await remove.waitFor({ state: 'detached' });
  assert.equal(await page.locator('[data-conversation-turn]').count(), 2, 'deleting another chat preserves current conversation');
  assert.equal(await input.inputValue(), 'Borrador que debe conservarse');
  assert.equal(await page.getByRole('button', { name: 'Quitar pendiente.txt' }).count(), 1);
  await page.getByRole('button', { name: 'Borrar conversación: Qué tengo pendiente' }).click();
  await page.getByRole('button', { name: 'Borrar definitivamente', exact: true }).click();
  await page.getByRole('button', { name: 'Borrar conversación: Qué tengo pendiente' }).waitFor({ state: 'detached' });
  assert.equal(await page.locator('[data-conversation-turn]').count(), 0);
  assert.equal(await input.inputValue(), ''); assert.equal(await page.getByRole('button', { name: 'Quitar pendiente.txt' }).count(), 0);
  assert.equal(await page.evaluate(() => sessionStorage.getItem('bria:conversation:user-kamila')), null);
  await page.reload(); await panel.waitFor(); await ready();
  assert.equal(await page.locator('[data-conversation-turn]').count(), 0);
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ passed: true, simulatedApi: true, checks: ['Confirmation above panel', 'Cancel preserves chat', 'Light/dark', 'Permanent delete clears active draft/history/session', 'Reload does not restore deleted chat'] }));
} finally { await browser.close(); await preview.close(); }
