import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright-core';
import { createBriaMascotPreview } from '../../scripts/preview-bria-mascot.js';

const preview = await createBriaMascotPreview({ port: 0 });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const out = path.resolve('output/bria-integrada');
const errors = []; page.on('pageerror', error => errors.push(error.message));
const legacyPortraitRequests = [];
// A previously cached public image must never determine Bria's identity again.
await page.route('**/brainstudio-mascot-tip.png', route => {
  legacyPortraitRequests.push(route.request().url());
  return route.abort();
});
const mascot = page.locator('[data-bria-assistant-trigger] [data-bria-mascot]');
const panel = page.locator('[data-bria-assistant-panel]');
const waitState = state => page.waitForFunction(value => document.querySelector('[data-bria-assistant-trigger] [data-bria-mascot]')?.dataset.briaState === value, state);
const ready = () => page.waitForFunction(() => !document.querySelector('[aria-label="Nueva conversación"]')?.disabled);
try {
  await mkdir(out, { recursive: true });
  await page.goto(preview.origin);
  await page.getByRole('button', { name: 'Preguntarle a Bria' }).waitFor({ timeout: 120000 });
  await page.getByRole('heading', { name: 'Clientes', exact: true }).waitFor();
  await page.waitForTimeout(400);
  assert.equal(await mascot.count(), 1, 'the mascot remains in the global Bria trigger');
  assert.equal(await page.locator('header [data-bria-assistant-trigger]').count(), 0, 'Bria no longer occupies the header');
  assert.equal(await page.locator('header [data-service-health-dot]').count(), 0, 'the separate check button is removed');
  assert.equal(await page.locator('header button[aria-label^="Abrir chat"]').count(), 1, 'team chat lives in the header');
  assert.equal(await page.locator('header button[aria-label="Cambiar tema"]').count(), 0, 'theme toggle leaves the main header');
  const themeToggle = page.locator('[data-sidebar-theme-toggle]');
  assert.equal(await themeToggle.count(), 1, 'theme toggle lives next to the Brainstudio name');
  const startsDark = await page.evaluate(() => document.documentElement.classList.contains('dark'));
  await themeToggle.click();
  assert.equal(await page.evaluate(() => document.documentElement.classList.contains('dark')), !startsDark);
  await themeToggle.click();
  await page.getByRole('button', { name: 'Recoger menú', exact: true }).click();
  assert.equal(await themeToggle.isVisible(), false, 'collapsed sidebar hides the theme control');
  await page.waitForTimeout(350);
  await page.screenshot({ path: path.join(out, 'sidebar-contraido-bria-pequena.png') });
  await page.getByRole('button', { name: 'Expandir menú', exact: true }).click();
  assert.equal(await themeToggle.isVisible(), true, 'expanded sidebar restores the theme control');
  await mascot.waitFor();
  await page.waitForFunction(() => document.querySelector('[data-bria-mascot]')?.dataset.briaReady === 'true');
  assert.equal(await mascot.evaluate(el => getComputedStyle(el).imageRendering), 'auto', 'Bria Chispa uses smooth edges');
  await waitState('idle');
  await page.screenshot({ path: path.join(out, 'plataforma-reposo.png') });
  await page.screenshot({ path: path.join(out, 'bria-abajo-derecha.png'), clip: { x: 1180, y: 620, width: 260, height: 280 } });
  await page.locator('header').first().screenshot({ path: path.join(out, 'cabecera-reposo.png') });
  const bounds = await mascot.boundingBox();
  assert.equal(bounds.width, 96, 'Bria uses a slightly smaller desktop canvas');
  const trigger = page.locator('[data-bria-assistant-trigger]');
  const floating = await trigger.boundingBox();
  const chatBubble = await page.getByRole('button', { name: /^Abrir chat/ }).boundingBox();
  assert.ok(floating.x > 1200 && floating.y > 600, 'Bria is at the bottom right');
  assert.ok(900 - floating.y - floating.height <= 40, 'Bria occupies the former chat corner');
  const bell = await page.getByRole('button', { name: 'Abrir notificaciones' }).boundingBox();
  assert.ok(chatBubble.x + chatBubble.width <= bell.x && Math.abs(chatBubble.y - bell.y) < 2, 'chat is immediately left of notifications');
  const healthIcon = page.locator('[data-service-health-icon]');
  for (const [overall, tone] of [['GREEN', 'text-status-positive-fg'], ['YELLOW', 'text-status-attention-fg'], ['RED', 'text-destructive']]) {
    await page.route('**/api/service-health/summary', route => route.fulfill({ json: { overall, troubled: [] } }));
    await page.reload();
    await page.locator(`[data-service-health-icon="${overall}"]`).waitFor();
    assert.ok((await healthIcon.getAttribute('class')).includes(tone));
    await page.locator('a[href="/salud-operativa"]').scrollIntoViewIfNeeded();
    await page.screenshot({ path: path.join(out, `salud-${overall.toLowerCase()}.png`) });
    await page.unroute('**/api/service-health/summary');
  }
  await page.route('**/api/service-health/summary', route => route.fulfill({ json: { overall: 'GREEN', troubled: [] } }));
  await page.reload(); await page.locator('[data-service-health-icon="GREEN"]').waitFor();
  await page.locator('a[href="/salud-operativa"]').scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(out, 'plataforma-reposo.png') });
  await page.locator('header').first().screenshot({ path: path.join(out, 'cabecera-reposo.png') });
  await page.getByRole('button', { name: /^Abrir chat/ }).click();
  const teamPanel = page.locator('.team-chat');
  await teamPanel.waitFor();
  await teamPanel.getByRole('heading', { name: '# General', exact: true }).waitFor();
  await teamPanel.getByText('Conectado', { exact: true }).waitFor();
  await teamPanel.locator('[contenteditable="true"]').fill('Borrador del equipo');
  await page.getByRole('button', { name: 'Cerrar chat', exact: true }).last().click();
  await page.waitForFunction(() => document.activeElement?.getAttribute('aria-label')?.startsWith('Abrir chat'));
  assert.equal(await page.locator('header button[aria-label^="Abrir chat"]').count(), 1, 'closing returns focus to the header trigger');
  await page.getByRole('button', { name: /^Abrir chat/ }).click();
  assert.match(await teamPanel.locator('[contenteditable="true"]').textContent(), /Borrador del equipo/, 'moving the trigger preserves the draft');
  await teamPanel.getByRole('button', { name: 'Cerrar chat', exact: true }).click();
  await page.getByRole('button', { name: 'Preguntarle a Bria' }).click(); await ready();
  assert.equal(await trigger.isVisible(), false, 'opening Bria chat hides the mascot');
  const portraits = panel.locator('[data-bria-portrait]');
  assert.equal(await portraits.count(), 1, 'the welcome retains Bria Chispa while the chat header shows only controls');
  await page.waitForFunction(() => [...document.querySelectorAll('[data-bria-assistant-panel] [data-bria-portrait]')].every(el => el.complete && el.naturalWidth > 0));
  const portraitSources = await portraits.evaluateAll(elements => elements.map(el => el.currentSrc));
  assert.equal(new Set(portraitSources).size, 1, 'chat portraits share exactly one approved asset');
  assert.match(portraitSources[0], /bria-chispa\/idle\.png/, 'the old public URL cannot display a stale design');
  assert.deepEqual(legacyPortraitRequests, [], 'the platform does not request the old mascot URL');
  await panel.getByRole('button', { name: 'Pantalla completa', exact: true }).click();
  assert.equal(await trigger.isVisible(), false, 'fullscreen chat also hides the mascot');
  await panel.getByRole('button', { name: 'Volver al panel lateral', exact: true }).click();
  await page.getByRole('button', { name: 'Expandir menú', exact: true }).click();
  await page.waitForTimeout(350);
  await page.screenshot({ path: path.join(out, 'bria-chat-abierto.png') });
  const input = page.getByLabel('Mensaje para Bria');
  await input.fill('¿Qué tengo pendiente hoy?'); await input.press('Enter');
  await waitState('work');
  await page.screenshot({ path: path.join(out, 'plataforma-trabajando.png') });
  await page.getByRole('button', { name: 'Cerrar Bria' }).click();
  assert.equal(await panel.isVisible(), false);
  assert.equal(await mascot.isVisible(), true, 'work remains visible with the panel closed');
  await mascot.screenshot({ path: path.join(out, 'mascota-trabajando.png') });
  await waitState('celebrate');
  await page.waitForTimeout(400);
  await mascot.screenshot({ path: path.join(out, 'mascota-celebrando.png') });
  await waitState('idle');
  assert.deepEqual(await mascot.boundingBox(), bounds, 'pose changes do not move the floating button');
  await page.getByRole('button', { name: 'Preguntarle a Bria' }).click(); await ready();
  await input.fill('esto da error'); await input.press('Enter'); await waitState('work');
  await panel.getByRole('alert').waitFor(); await waitState('idle');
  assert.equal(await input.inputValue(), 'esto da error');
  await input.fill('¿Cómo va la parrilla de Endova?'); await input.press('Enter'); await waitState('work');
  await panel.getByText('Una parte de la consulta falló.', { exact: false }).waitFor(); await waitState('idle');
  await page.getByRole('button', { name: 'Cerrar Bria' }).click();
  await page.reload(); await waitState('idle');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.waitForFunction(() => document.querySelector('[data-bria-mascot]')?.dataset.briaAnimating === 'false');
  const before = await mascot.evaluate(el => el.toDataURL());
  await page.waitForTimeout(350);
  assert.equal(await mascot.evaluate(el => el.toDataURL()), before, 'reduced motion stops the animation');
  await page.evaluate(() => document.documentElement.classList.add('dark'));
  await page.locator('a[href="/salud-operativa"]').scrollIntoViewIfNeeded();
  assert.ok((await healthIcon.getAttribute('class')).includes('text-status-positive-fg'), 'collapsed active/hover styles do not override the service status');
  await page.waitForTimeout(300);
  await page.screenshot({ path: path.join(out, 'muestra-oscura.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(400);
  const mobileBria = await trigger.boundingBox(), mobileChat = await page.getByRole('button', { name: /^Abrir chat/ }).boundingBox();
  assert.equal(mobileBria.width, 80, 'Bria is also a little smaller on mobile');
  assert.ok(mobileBria.x >= 0 && mobileBria.x + mobileBria.width <= 390);
  assert.ok(mobileChat.y < 64 && 844 - mobileBria.y - mobileBria.height <= 40, 'chat is in the header and Bria in the corner on mobile');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.screenshot({ path: path.join(out, 'muestra-movil.png') });
  const mobileBell = await page.getByRole('button', { name: 'Abrir notificaciones' }).boundingBox();
  assert.ok(mobileChat.x + mobileChat.width <= mobileBell.x && Math.abs(mobileChat.y - mobileBell.y) < 2);
  await page.getByRole('button', { name: /^Abrir chat/ }).click(); await teamPanel.waitFor();
  await teamPanel.getByRole('button', { name: 'Cerrar chat', exact: true }).click();
  await page.waitForFunction(() => document.activeElement?.getAttribute('aria-label')?.startsWith('Abrir chat'));
  await page.getByRole('button', { name: 'Abrir menú', exact: true }).click();
  await themeToggle.waitFor();
  await themeToggle.click();
  assert.equal(await page.evaluate(() => document.documentElement.classList.contains('dark')), true, 'mobile drawer uses the same stored theme');
  await page.screenshot({ path: path.join(out, 'tema-barra-lateral-movil.png') });
  await page.getByRole('button', { name: 'Cerrar menú', exact: true }).click();
  await page.getByRole('button', { name: 'Preguntarle a Bria' }).click();
  await panel.waitFor();
  assert.equal(await trigger.isVisible(), false, 'mobile chat hides Bria until it closes');
  await page.screenshot({ path: path.join(out, 'bria-chat-movil.png') });
  await page.getByRole('button', { name: 'Cerrar Bria' }).click();
  await page.waitForFunction(() => document.activeElement?.hasAttribute('data-bria-assistant-trigger'));
  assert.equal(await trigger.isVisible(), true, 'closing mobile chat restores Bria');
  assert.deepEqual(await trigger.boundingBox(), mobileBria, 'Bria returns to her corner');
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ passed: true, simulatedApi: true, checks: ['Bria hides when chat opens and returns when it closes in desktop/fullscreen/mobile', 'sidebar theme toggle in expanded/collapsed/mobile layouts', 'team chat left of notifications', 'chat draft and return focus', 'sidebar health green/yellow/red', 'work and single confirmed celebration', 'error and partial failure', 'no replay on reload', 'reduced motion', 'dark and mobile'] }));
} finally { await browser.close(); await preview.close(); }
