import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
const base = process.env.FINANCIAL_DEMO_URL || 'http://127.0.0.1:3006/tests/fixtures/financial-integrity.html';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
  await page.goto(base);
  await page.getByRole('button', { name: /Cartera/ }).click();
  const row = page.getByRole('button', { name: /Cliente de muestra/ });
  await row.waitFor();
  assert.match(await row.innerText(), /800[.,]000/);
  await page.getByText('1 deudores', { exact: true }).waitFor();
  assert.match(await row.innerText(), /Sin vencimiento/);
  await row.click();
  assert.match(await page.locator('body').innerText(), /septiembre de 2026/i);
  await page.getByRole('button', { name: 'Registrar pago', exact: true }).click();
  await page.getByLabel('Origen del pago').selectOption('EXISTING');
  await page.getByLabel('Ingreso registrado').selectOption('demo-record-0');
  assert.match(await page.getByRole('dialog').innerText(), /No se creará otro ingreso/);
  const controlsAlign = await page.getByRole('dialog').evaluate(dialog => {
    const labels = [...dialog.querySelectorAll('label')];
    const dateY = labels.find(label => label.textContent.startsWith('Fecha')).querySelector('input').getBoundingClientRect().y;
    const accountY = labels.find(label => label.textContent.startsWith('Cuenta')).querySelector('select').getBoundingClientRect().y;
    return Math.abs(dateY - accountY) <= 1;
  });
  assert.ok(controlsAlign, 'date and account controls must align below their labels');
  await page.screenshot({ path: 'output/financial-payment-preview.png', animations: 'disabled' });
  await page.getByRole('button', { name: 'Guardar pago', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await row.innerText(), /600[.,]000/);
  await page.getByRole('button', { name: 'Clientes', exact: true }).click();
  assert.match(await page.locator('tbody').innerText(), /600[.,]000/);
  await page.getByRole('button', { name: /Cartera/ }).click();
  await page.screenshot({ path: 'output/financial-cartera-preview.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Cambiar tema' }).click();
  await page.screenshot({ path: 'output/financial-cartera-dark.png', fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true, 'mobile must not overflow the viewport');
  await row.scrollIntoViewIfNeeded();
  await page.evaluate(async () => {
    await Promise.all(document.getAnimations().filter(animation => animation.effect?.getTiming().iterations !== Infinity).map(animation => animation.finished.catch(() => {})));
    await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)));
  });
  await page.screenshot({ path: 'output/financial-cartera-mobile.png', animations: 'disabled' });
  await page.setViewportSize({ width: 1440, height: 1050 });
  await page.getByRole('button', { name: 'Cambiar tema' }).click();
  await page.getByRole('button', { name: 'Movimientos', exact: true }).click();
  const ledgerPages = page.getByRole('navigation', { name: 'Paginación de movimientos' });
  await ledgerPages.getByText('Página 1 de 3').waitFor();
  await ledgerPages.getByRole('button', { name: 'Siguiente' }).click();
  await ledgerPages.getByText('Página 2 de 3').waitFor();
  await ledgerPages.getByRole('button', { name: 'Siguiente' }).click();
  await ledgerPages.getByText('Página 3 de 3').waitFor();
  assert.match(await page.locator('tbody').innerText(), /Ingreso de muestra 62/);
  await page.screenshot({ path: 'output/financial-ledger-preview.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Conciliación', exact: true }).click();
  await page.getByText('Conciliado', { exact: true }).waitFor();
  const bankPages = page.getByRole('navigation', { name: 'Paginación de conciliación' });
  for (let i = 0; i < 4; i++) await bankPages.getByRole('button', { name: 'Siguiente' }).click();
  await bankPages.getByText('Página 5 de 5').waitFor();
  await page.getByText('Movimiento bancario 90', { exact: true }).waitFor();
  await page.screenshot({ path: 'output/financial-bank-preview.png', fullPage: true, animations: 'disabled' });
  await page.goto(`${base}?paymentError=1`);
  await page.getByRole('button', { name: /Cartera/ }).click();
  await page.getByRole('button', { name: /Cliente de muestra/ }).click();
  await page.getByRole('button', { name: 'Registrar pago', exact: true }).click();
  await page.getByLabel('Concepto del ingreso').selectOption('SERVICIO');
  await page.getByRole('dialog').getByLabel('Cuenta').selectOption('demo-account');
  await page.getByRole('button', { name: 'Guardar pago', exact: true }).click();
  await page.getByRole('dialog').getByText('Pago no guardado (simulado)').waitFor();
  assert.equal(await page.getByText('Pago de cartera registrado.').count(), 0);
  await page.goto(`${base}?carteraError=1`);
  await page.getByRole('button', { name: /Cartera/ }).click();
  await page.getByText('No fue posible cargar la cartera.').waitFor();
  assert.equal(await page.getByText('¡Cartera 100% al día!').count(), 0);
  await page.goto(`${base}?viewer=reader`);
  await page.getByRole('button', { name: /Cartera/ }).click();
  await page.getByRole('button', { name: /Cliente de muestra/ }).click();
  assert.equal(await page.getByRole('button', { name: 'Registrar pago', exact: true }).count(), 0);
  assert.equal(await page.getByLabel('Estado de seguimiento').isDisabled(), true);
  await page.goto(`${base}?legacyPaid=1`);
  await page.getByRole('button', { name: /Cartera/ }).click();
  const legacyRow = page.getByRole('button', { name: /Cliente de muestra/ });
  assert.match(await legacyRow.innerText(), /Saldo por verificar/);
  assert.doesNotMatch(await legacyRow.innerText(), /Sin saldo pendiente/);
  await legacyRow.click();
  assert.equal(await page.getByRole('button', { name: 'Registrar pago', exact: true }).count(), 0);
  assert.equal(await page.getByLabel('Estado de seguimiento').isDisabled(), true);
  await page.getByRole('alert').filter({ hasText: /históricos marcados como pagados/ }).waitFor();
  await page.screenshot({ path: 'output/financial-legacy-review.png', fullPage: true, animations: 'disabled' });
  console.log('Financial browser: balances, existing income application, cache, read-only, dates, errors, light/dark/mobile verified.');
} finally { await browser.close(); }
