import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
const base = process.env.FINANCIAL_DEMO_URL || 'http://127.0.0.1:3006/tests/fixtures/financial-integrity.html';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.setDefaultTimeout(8000);
  const open = async suffix => {
    await page.goto(base + suffix);
    await page.getByRole('button', { name: 'Clientes', exact: true }).click();
    await page.getByRole('button', { name: 'Ver estado de cuenta', exact: true }).click();
    await page.getByRole('dialog').waitFor();
  };
  await open('');
  const dialog = page.getByRole('dialog');
  await dialog.getByText('Saldo pendiente', { exact: true }).waitFor();
  assert.match(await dialog.innerText(), /800[.,]000/);
  assert.match(await dialog.innerText(), /septiembre de 2026/);
  await dialog.getByText('Ver abonos (1)', { exact: true }).click();
  await dialog.getByText('Banco de muestra', { exact: true }).waitFor();
  assert.equal(await dialog.getByRole('link', { name: 'Ver soporte' }).getAttribute('href'), 'https://example.invalid/soporte.pdf');
  await page.screenshot({ path: 'output/financial-client-statement.png', animations: 'disabled' });
  await dialog.getByRole('button', { name: 'Ingresos registrados', exact: true }).click();
  await dialog.getByText('Adicional ya registrado', { exact: true }).waitFor();
  assert.equal(await dialog.locator('a[href^="javascript:"]').count(), 0);
  const pages = dialog.getByRole('navigation', { name: 'Paginación del estado de cuenta' });
  await pages.getByRole('button', { name: 'Siguiente' }).click();
  await pages.getByText('Página 2', { exact: true }).waitFor();
  await pages.getByRole('button', { name: 'Siguiente' }).click();
  await dialog.getByText('Ingreso de muestra 62', { exact: true }).waitFor();
  assert.equal(await pages.getByRole('button', { name: 'Siguiente' }).isDisabled(), true);
  await dialog.getByRole('button', { name: 'Obligaciones y abonos', exact: true }).click();
  await dialog.getByText('Saldo pendiente', { exact: true }).waitFor();
  await page.evaluate(() => document.documentElement.classList.add('dark'));
  await page.screenshot({ path: 'output/financial-client-statement-dark.png', animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(async () => { await Promise.all(document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).map(a => a.finished.catch(() => {}))); });
  assert.equal(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth + 1), true);
  await page.screenshot({ path: 'output/financial-client-statement-mobile.png', animations: 'disabled' });
  await dialog.getByRole('button', { name: 'Cerrar', exact: true }).click();
  await dialog.waitFor({ state: 'hidden' });
  await open('?viewer=reader');
  await dialog.getByText('Saldo pendiente', { exact: true }).waitFor();
  await dialog.getByRole('button', { name: 'Cerrar', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Vincular', exact: true }).count(), 0);
  await open('?statementError=1');
  await dialog.getByRole('alert').waitFor();
  assert.equal(await dialog.getByText('No hay obligaciones registradas para este año.').count(), 0);
  await open('?legacyPaid=1');
  await dialog.getByText('Saldo por verificar', { exact: true }).waitFor();
  console.log('Client statement: scope, applications, income pages, read-only, errors, support links, light/dark/mobile verified.');
} finally { await browser.close(); }
