import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
import { createWelcomePreview } from '../../scripts/preview-welcome.js';
let browser, preview;
test.before(async () => { preview = await createWelcomePreview({ port: 0 }); browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true }); });
test.after(async () => { await browser?.close(); await preview?.close(); });
test('runtime acknowledges on the server, offers the allowed guide and stops when permission is revoked', async () => {
  const page = await browser.newPage(); page.setDefaultTimeout(10000);
  await page.goto(`${preview.origin}/tests/fixtures/onboarding-runtime.html`);
  const welcome = page.getByRole('dialog', { name: '¡Qué bueno tenerte aquí, Persona!' }); await welcome.waitFor();
  await page.getByRole('button', { name: 'Vamos a empezar' }).click();
  assert.equal(await welcome.isVisible(), true);
  await welcome.waitFor({ state: 'hidden' });
  assert.equal(await page.getByRole('dialog').count(), 0);
  await page.getByRole('link', { name: 'Cotizaciones' }).click();
  const guide = page.getByRole('dialog', { name: 'Cotizaciones, paso a paso' }); await guide.waitFor();
  await page.getByRole('button', { name: 'Omitir guía' }).click();
  await guide.waitFor({ state: 'hidden' });
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.getByRole('link', { name: 'Cotizaciones' }).click();
  assert.equal(await guide.count(), 0);
  await page.getByRole('button', { name: 'Ver guía', exact: true }).click(); await guide.waitFor();
  await page.keyboard.press('Escape'); await guide.waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Revocar permiso (prueba)' }).click();
  await page.getByRole('button', { name: 'Ver guía', exact: true }).waitFor({ state: 'hidden' });
  await page.close();
});
test('save error leaves welcome visible, explains failure and supports retry', async () => {
  const page = await browser.newPage(); page.setDefaultTimeout(10000);
  await page.goto(`${preview.origin}/tests/fixtures/onboarding-runtime.html?error`);
  await page.getByRole('button', { name: 'Vamos a empezar' }).click();
  await page.getByRole('alert').filter({ hasText: 'Guardado de prueba rechazado' }).waitFor();
  assert.equal(await page.getByRole('dialog').isVisible(), true);
  await page.getByRole('button', { name: 'Vamos a empezar' }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.close();
});
test('neither welcome nor a direct module URL offers a denied guide', async () => {
  const page = await browser.newPage(); page.setDefaultTimeout(10000);
  await page.goto(`${preview.origin}/tests/fixtures/onboarding-runtime.html?denied`);
  const welcome = page.getByRole('dialog'); await welcome.waitFor();
  assert.equal(await welcome.getByText('Cotizaciones', { exact: true }).count(), 0);
  await page.getByRole('button', { name: 'Vamos a empezar' }).click(); await welcome.waitFor({ state: 'hidden' });
  await page.getByRole('link', { name: 'Cotizaciones' }).click();
  assert.equal(await page.getByRole('dialog').count(), 0);
  assert.equal(await page.getByRole('button', { name: 'Ver guía', exact: true }).count(), 0);
  await page.close();
});
