import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
const base = process.env.QUOTATION_DEMO_URL || 'http://127.0.0.1:3007/tests/fixtures/quotation-proposal.html';
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.setDefaultTimeout(10000);
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(base, { timeout: 60000, waitUntil: 'domcontentloaded' });
  await page.getByRole('button', { name: 'Añadir servicio personalizado', exact: true }).click();
  await page.getByLabel('Nombre del servicio 8').fill('Asesoría personalizada');
  const rich = page.getByRole('group', { name: 'Descripción del servicio 8', exact: true });
  await rich.locator('[contenteditable="true"]').fill('Alcance escrito sin producto de catálogo.');
  await rich.getByRole('button', { name: 'Añadir enlace' }).click();
  await page.getByLabel('Texto del enlace').fill('Documento técnico');
  await page.getByLabel('Dirección web').fill('https://example.com/documento');
  await page.getByRole('button', { name: 'Insertar enlace' }).click();
  await page.getByRole('button', { name: 'Guardar como Borrador' }).click();
  await page.getByText('Borrador guardado', { exact: true }).waitFor();
  const custom = (await page.evaluate(() => window.__quotationDemo())).items[7];
  assert.match(custom.descriptionHtml, /Alcance escrito/); assert.match(custom.descriptionHtml, /https:\/\/example.com\/documento/); assert.equal(custom.serviceId, undefined);
  await page.getByText('Borrador guardado', { exact: true }).waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Eliminar servicio 8' }).click();
  await page.getByText('Plan de pagos', { exact: true }).click();
  await page.getByLabel('Nombre de cuota 1').fill('Reserva del proyecto');
  await page.getByLabel('Confirmo que las condiciones').check();
  await page.getByRole('button', { name: 'Guardar como Borrador' }).click();
  await page.getByText('Borrador guardado', { exact: true }).waitFor();
  assert.equal((await page.evaluate(() => window.__quotationDemo())).proposal_details.paymentPlans[0].installments[0].label, 'Reserva del proyecto');
  await page.getByText('Borrador guardado', { exact: true }).waitFor({ state: 'hidden' });
  await page.screenshot({ path: 'output/quotation-proposal-editor.png' });
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'PDF guardado' }).click();
  assert.equal((await download).suggestedFilename(), 'SunPartners-muestra-local.pdf');
  await page.getByRole('link', { name: 'Vista del cliente' }).click();
  await page.getByRole('heading', { name: 'Plan de pagos' }).waitFor();
  assert.match(await page.locator('body').innerText(), /8\.330\.000/);
  assert.equal(await page.getByText('Inversión mensual', { exact: true }).count(), 0);
  assert.equal(await page.getByText('Desarrollo 2 · Remisiones', { exact: true }).count() > 0, true);
  const links = page.locator('a[href="https://example.com/"]'); assert.equal(await links.count(), 1);
  await page.getByRole('heading', { name: 'Plan de pagos' }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'output/quotation-proposal-payments.png' });
  await page.getByRole('button', { name: 'Cambiar tema' }).click();
  await page.getByRole('heading', { name: 'Plan de pagos' }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'output/quotation-proposal-dark.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('heading', { name: 'Plan de pagos' }).scrollIntoViewIfNeeded();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true);
  await page.screenshot({ path: 'output/quotation-proposal-mobile.png' });
  await page.getByRole('link', { name: 'Editar propuesta' }).click();
  await page.getByRole('button', { name: 'Añadir servicio personalizado' }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true);
  await page.screenshot({ path: 'output/quotation-proposal-editor-mobile.png' });
  await page.goto(base + '?saveError=1', { waitUntil: 'domcontentloaded' });
  await page.getByLabel('Nombre del servicio 1').fill('No debe guardarse');
  await page.getByRole('button', { name: 'Guardar como Borrador' }).click();
  await page.getByText('Error de guardado simulado', { exact: true }).waitFor();
  assert.notEqual((await page.evaluate(() => window.__quotationDemo())).items[0].name, 'No debe guardarse');
  assert.equal(await page.getByText('Borrador guardado', { exact: true }).count(), 0);
  assert.deepEqual(errors, []);
  console.log('Quote editor, custom services, payment persistence, public view and responsive themes verified.');
} finally { await browser.close(); }
