import test from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { briaTestDatabaseUrl } from './support/briaTestDatabase.js';
import { createBriaKnowledgeRepository } from '../src/services/briaKnowledgeRepository.js';
import { createBriaConversationRepository } from '../src/services/briaConversationRepository.js';
const connectionString = briaTestDatabaseUrl();
test('real PostgreSQL preserves corrections, detects concurrent writes and undoes without deleting history', { skip: !connectionString }, async () => {
  const pool = new pg.Pool({ connectionString, max: 2 });
  const workspace = `test:${randomUUID()}`, actor = { ref: 'test:owner', name: 'Prueba', role: 'ADMIN', accountIds: [] };
  try {
    if (!(await pool.query("SELECT to_regclass('bria_memory.learnings') IS NOT NULL AS ready")).rows[0].ready) await pool.query(await readFile(new URL('../scripts/sql/bria-knowledge.sql', import.meta.url), 'utf8'));
    if (!(await pool.query("SELECT to_regclass('bria_memory.conversations') IS NOT NULL AS ready")).rows[0].ready) await pool.query(await readFile(new URL('../scripts/sql/bria-conversations.sql', import.meta.url), 'utf8'));
    const repo = createBriaKnowledgeRepository({ pool, workspace });
    const chats = createBriaConversationRepository({ pool, workspace });
    const chat = await chats.create(actor);
    await chats.append(actor, chat.id, 0, 'Pregunta ficticia', { answer: 'Respuesta ficticia', sources: [] });
    assert.equal((await chats.get(actor, chat.id)).turns.length, 2);
    assert.equal(await chats.get({ ...actor, ref: 'other' }, chat.id), null);
    await assert.rejects(() => chats.append(actor, chat.id, 0, 'Concurrente', { answer: 'No debe guardarse' }), { status: 409 });
    assert.equal((await createBriaConversationRepository({ pool, workspace }).list(actor))[0].title, 'Pregunta ficticia');
    const input = { scope: 'ACCOUNT', entity: 'Cuenta de prueba', topic: 'Revisión', text: 'Revisión uno.', kind: 'CONFIRMED', validFrom: '2026-10-07', validUntil: null };
    const created = await repo.save({ actor, learning: input });
    assert.equal(created.revision, 1);
    const changed = await repo.save({ actor, learning: { ...input, text: 'Revisión dos.' }, id: created.id, expectedRevision: 1 });
    assert.equal(changed.revision, 2);
    await assert.rejects(() => repo.save({ actor, learning: input, id: created.id, expectedRevision: 1 }), { status: 409 });
    const undone = await repo.undo({ actor, id: created.id, expectedRevision: 2 });
    assert.equal(undone.text, 'Revisión uno.'); assert.equal(undone.revision, 3);
    assert.equal((await repo.history(actor, created.id)).length, 3);
    const reopened = createBriaKnowledgeRepository({ pool, workspace });
    assert.equal((await reopened.list(actor))[0].text, 'Revisión uno.');
    const revoked = await repo.revoke({ actor, id: created.id, expectedRevision: 3 });
    assert.equal(revoked.status, 'REVOKED');
    assert.equal((await repo.history(actor, created.id)).length, 4);
    const personal = await repo.save({ actor, learning: { ...input, scope: 'PERSONAL', entity: 'Personal', topic: 'Preferencia' } });
    assert.equal((await repo.list({ ...actor, ref: 'another-admin' })).some(row => row.id === personal.id), false);
    await assert.rejects(() => repo.undo({ actor: { ...actor, ref: 'another-admin' }, id: personal.id, expectedRevision: 1 }), { status: 404 });
    const source = { id: 'drive:test', kind: 'drive', title: 'Cuenta de prueba', date: '2026-10-07', locator: null, digest: 'one', body: 'Texto de prueba de coordinación y producción.', status: 'indexed' };
    assert.equal((await repo.importSource(source)).changed, true);
    assert.equal((await repo.importSource(source)).changed, false);
    assert.match((await repo.search({ role: 'ADMIN' }, 'coordinación'))[0].excerpt, /coordinación/);
    assert.equal((await repo.search({ role: 'PROJECT_MANAGER' }, 'coordinación')).length, 0);
    assert.equal((await repo.read({ role: 'ADMIN' }, source.id)).excerpt, source.body);
    const long = { ...source, id: 'drive:long', digest: 'long', body: 'Texto de referencia. '.repeat(500) + 'Detalle importante: exactitudconversacional.' };
    await repo.importSource(long);
    assert.match((await repo.search({ role: 'ADMIN' }, 'exactitudconversacional'))[0].excerpt, /exactitudconversacional/);
    await repo.importSource({ ...source, digest: 'two', body: 'Texto actualizado.' });
    assert.equal((await pool.query('SELECT count(*)::int AS n FROM bria_memory.source_versions WHERE workspace=$1 AND source_id=$2', [workspace, source.id])).rows[0].n, 2);
    await repo.excludeMissing([]);
    assert.equal(await repo.read({ role: 'ADMIN' }, source.id), null);
  } finally {
    await pool.query('DELETE FROM bria_memory.conversations WHERE workspace=$1', [workspace]);
    await pool.query('DELETE FROM bria_memory.learning_events WHERE learning_id IN (SELECT id FROM bria_memory.learnings WHERE workspace=$1)', [workspace]);
    for (const table of ['learnings', 'source_search', 'source_versions', 'sources']) await pool.query(`DELETE FROM bria_memory.${table} WHERE workspace=$1`, [workspace]);
    await pool.end();
  }
});
