import React, { forwardRef } from 'react';
import { HugeiconsIcon } from '@hugeicons/react';
import Activity01IconData from '@hugeicons/core-free-icons/Activity01Icon';
import Add01IconData from '@hugeicons/core-free-icons/Add01Icon';
import AddCircleIconData from '@hugeicons/core-free-icons/AddCircleIcon';
import Alert01IconData from '@hugeicons/core-free-icons/Alert01Icon';
import AlertCircleIconData from '@hugeicons/core-free-icons/AlertCircleIcon';
import AnalyticsDownIconData from '@hugeicons/core-free-icons/AnalyticsDownIcon';
import AnalyticsUpIconData from '@hugeicons/core-free-icons/AnalyticsUpIcon';
import ArchiveIconData from '@hugeicons/core-free-icons/ArchiveIcon';
import ArrowDownRight01IconData from '@hugeicons/core-free-icons/ArrowDownRight01Icon';
import ArrowLeft01IconData from '@hugeicons/core-free-icons/ArrowLeft01Icon';
import ArrowRight01IconData from '@hugeicons/core-free-icons/ArrowRight01Icon';
import ArrowUpRight01IconData from '@hugeicons/core-free-icons/ArrowUpRight01Icon';
import AttachmentIconData from '@hugeicons/core-free-icons/AttachmentIcon';
import Award01IconData from '@hugeicons/core-free-icons/Award01Icon';
import BarChartIconData from '@hugeicons/core-free-icons/BarChartIcon';
import BellIconData from '@hugeicons/core-free-icons/BellIcon';
import BoldIconData from '@hugeicons/core-free-icons/BoldIcon';
import BookOpen01IconData from '@hugeicons/core-free-icons/BookOpen01Icon';
import BotIconData from '@hugeicons/core-free-icons/BotIcon';
import BrainIconData from '@hugeicons/core-free-icons/BrainIcon';
import BubbleChatIconData from '@hugeicons/core-free-icons/BubbleChatIcon';
import Building02IconData from '@hugeicons/core-free-icons/Building02Icon';
import BulbIconData from '@hugeicons/core-free-icons/BulbIcon';
import Calendar01IconData from '@hugeicons/core-free-icons/Calendar01Icon';
import CalendarClockIconData from '@hugeicons/core-free-icons/CalendarClockIcon';
import CalendarDaysIconData from '@hugeicons/core-free-icons/CalendarDaysIcon';
import Camera01IconData from '@hugeicons/core-free-icons/Camera01Icon';
import Cancel01IconData from '@hugeicons/core-free-icons/Cancel01Icon';
import ChampionIconData from '@hugeicons/core-free-icons/ChampionIcon';
import CheckIconData from '@hugeicons/core-free-icons/CheckIcon';
import CheckListIconData from '@hugeicons/core-free-icons/CheckListIcon';
import CheckmarkCircle01IconData from '@hugeicons/core-free-icons/CheckmarkCircle01Icon';
import CheckmarkCircle02IconData from '@hugeicons/core-free-icons/CheckmarkCircle02Icon';
import CheckmarkSquare01IconData from '@hugeicons/core-free-icons/CheckmarkSquare01Icon';
import ChevronDownIconData from '@hugeicons/core-free-icons/ChevronDownIcon';
import ChevronLeftIconData from '@hugeicons/core-free-icons/ChevronLeftIcon';
import ChevronRightIconData from '@hugeicons/core-free-icons/ChevronRightIcon';
import ChevronUpIconData from '@hugeicons/core-free-icons/ChevronUpIcon';
import CircleArrowUp01IconData from '@hugeicons/core-free-icons/CircleArrowUp01Icon';
import CircleDotIconData from '@hugeicons/core-free-icons/CircleDotIcon';
import CircleIconData from '@hugeicons/core-free-icons/CircleIcon';
import ClipboardListIconData from '@hugeicons/core-free-icons/ClipboardListIcon';
import Clock01IconData from '@hugeicons/core-free-icons/Clock01Icon';
import CloudUploadIconData from '@hugeicons/core-free-icons/CloudUploadIcon';
import Coffee01IconData from '@hugeicons/core-free-icons/Coffee01Icon';
import ColorPickerIconData from '@hugeicons/core-free-icons/ColorPickerIcon';
import CompassIconData from '@hugeicons/core-free-icons/CompassIcon';
import ComputerIconData from '@hugeicons/core-free-icons/ComputerIcon';
import CopyIconData from '@hugeicons/core-free-icons/CopyIcon';
import CpuIconData from '@hugeicons/core-free-icons/CpuIcon';
import Cursor02IconData from '@hugeicons/core-free-icons/Cursor02Icon';
import DashboardSquare01IconData from '@hugeicons/core-free-icons/DashboardSquare01Icon';
import DatabaseIconData from '@hugeicons/core-free-icons/DatabaseIcon';
import Delete02IconData from '@hugeicons/core-free-icons/Delete02Icon';
import DollarSignIconData from '@hugeicons/core-free-icons/DollarSignIcon';
import Download01IconData from '@hugeicons/core-free-icons/Download01Icon';
import Edit01IconData from '@hugeicons/core-free-icons/Edit01Icon';
import ExternalLinkIconData from '@hugeicons/core-free-icons/ExternalLinkIcon';
import EyeIconData from '@hugeicons/core-free-icons/EyeIcon';
import Facebook01IconData from '@hugeicons/core-free-icons/Facebook01Icon';
import File01IconData from '@hugeicons/core-free-icons/File01Icon';
import File02IconData from '@hugeicons/core-free-icons/File02Icon';
import FileArchiveIconData from '@hugeicons/core-free-icons/FileArchiveIcon';
import FileAudioIconData from '@hugeicons/core-free-icons/FileAudioIcon';
import FileChartColumnIconData from '@hugeicons/core-free-icons/FileChartColumnIcon';
import FileSpreadsheetIconData from '@hugeicons/core-free-icons/FileSpreadsheetIcon';
import FileVideoIconData from '@hugeicons/core-free-icons/FileVideoIcon';
import FilterIconData from '@hugeicons/core-free-icons/FilterIcon';
import FlameIconData from '@hugeicons/core-free-icons/FlameIcon';
import Folder01IconData from '@hugeicons/core-free-icons/Folder01Icon';
import FolderOpenIconData from '@hugeicons/core-free-icons/FolderOpenIcon';
import GlobeIconData from '@hugeicons/core-free-icons/GlobeIcon';
import GridIconData from '@hugeicons/core-free-icons/GridIcon';
import HandIconData from '@hugeicons/core-free-icons/HandIcon';
import Heading01IconData from '@hugeicons/core-free-icons/Heading01Icon';
import Heading02IconData from '@hugeicons/core-free-icons/Heading02Icon';
import Heading03IconData from '@hugeicons/core-free-icons/Heading03Icon';
import HelpCircleIconData from '@hugeicons/core-free-icons/HelpCircleIcon';
import HierarchyFilesIconData from '@hugeicons/core-free-icons/HierarchyFilesIcon';
import HighlighterIconData from '@hugeicons/core-free-icons/HighlighterIcon';
import HistoryIconData from '@hugeicons/core-free-icons/HistoryIcon';
import Image01IconData from '@hugeicons/core-free-icons/Image01Icon';
import InformationCircleIconData from '@hugeicons/core-free-icons/InformationCircleIcon';
import InstagramIconData from '@hugeicons/core-free-icons/InstagramIcon';
import Key01IconData from '@hugeicons/core-free-icons/Key01Icon';
import Key02IconData from '@hugeicons/core-free-icons/Key02Icon';
import Layers01IconData from '@hugeicons/core-free-icons/Layers01Icon';
import Layout01IconData from '@hugeicons/core-free-icons/Layout01Icon';
import LayoutGridIconData from '@hugeicons/core-free-icons/LayoutGridIcon';
import LeftToRightListNumberIconData from '@hugeicons/core-free-icons/LeftToRightListNumberIcon';
import Link01IconData from '@hugeicons/core-free-icons/Link01Icon';
import Link02IconData from '@hugeicons/core-free-icons/Link02Icon';
import ListViewIconData from '@hugeicons/core-free-icons/ListViewIcon';
import Loading03IconData from '@hugeicons/core-free-icons/Loading03Icon';
import LockIconData from '@hugeicons/core-free-icons/LockIcon';
import LockKeyIconData from '@hugeicons/core-free-icons/LockKeyIcon';
import Logout01IconData from '@hugeicons/core-free-icons/Logout01Icon';
import Mail01IconData from '@hugeicons/core-free-icons/Mail01Icon';
import MailSend01IconData from '@hugeicons/core-free-icons/MailSend01Icon';
import MapsIconData from '@hugeicons/core-free-icons/MapsIcon';
import Maximize02IconData from '@hugeicons/core-free-icons/Maximize02Icon';
import Megaphone01IconData from '@hugeicons/core-free-icons/Megaphone01Icon';
import Menu01IconData from '@hugeicons/core-free-icons/Menu01Icon';
import Message01IconData from '@hugeicons/core-free-icons/Message01Icon';
import Message02IconData from '@hugeicons/core-free-icons/Message02Icon';
import Mic01IconData from '@hugeicons/core-free-icons/Mic01Icon';
import Minimize02IconData from '@hugeicons/core-free-icons/Minimize02Icon';
import MoonIconData from '@hugeicons/core-free-icons/MoonIcon';
import MoreHorizontalIconData from '@hugeicons/core-free-icons/MoreHorizontalIcon';
import MoreVerticalIconData from '@hugeicons/core-free-icons/MoreVerticalIcon';
import MusicNote01IconData from '@hugeicons/core-free-icons/MusicNote01Icon';
import PencilEdit02IconData from '@hugeicons/core-free-icons/PencilEdit02Icon';
import PencilIconData from '@hugeicons/core-free-icons/PencilIcon';
import PieChartIconData from '@hugeicons/core-free-icons/PieChartIcon';
import PlayCircleIconData from '@hugeicons/core-free-icons/PlayCircleIcon';
import Presentation01IconData from '@hugeicons/core-free-icons/Presentation01Icon';
import QrCodeIconData from '@hugeicons/core-free-icons/QrCodeIcon';
import Radar01IconData from '@hugeicons/core-free-icons/Radar01Icon';
import RedoIconData from '@hugeicons/core-free-icons/RedoIcon';
import RefreshIconData from '@hugeicons/core-free-icons/RefreshIcon';
import RotateLeft01IconData from '@hugeicons/core-free-icons/RotateLeft01Icon';
import SaveIconData from '@hugeicons/core-free-icons/SaveIcon';
import Search01IconData from '@hugeicons/core-free-icons/Search01Icon';
import SecurityCheckIconData from '@hugeicons/core-free-icons/SecurityCheckIcon';
import Settings01IconData from '@hugeicons/core-free-icons/Settings01Icon';
import Settings02IconData from '@hugeicons/core-free-icons/Settings02Icon';
import Share02IconData from '@hugeicons/core-free-icons/Share02Icon';
import SmartPhone01IconData from '@hugeicons/core-free-icons/SmartPhone01Icon';
import SparklesIconData from '@hugeicons/core-free-icons/SparklesIcon';
import StarIconData from '@hugeicons/core-free-icons/StarIcon';
import StickyNote01IconData from '@hugeicons/core-free-icons/StickyNote01Icon';
import StopCircleIconData from '@hugeicons/core-free-icons/StopCircleIcon';
import Sun01IconData from '@hugeicons/core-free-icons/Sun01Icon';
import Table01IconData from '@hugeicons/core-free-icons/Table01Icon';
import Tag01IconData from '@hugeicons/core-free-icons/Tag01Icon';
import Target01IconData from '@hugeicons/core-free-icons/Target01Icon';
import TextIconData from '@hugeicons/core-free-icons/TextIcon';
import TextItalicIconData from '@hugeicons/core-free-icons/TextItalicIcon';
import TextUnderlineIconData from '@hugeicons/core-free-icons/TextUnderlineIcon';
import ThermometerIconData from '@hugeicons/core-free-icons/ThermometerIcon';
import Upload01IconData from '@hugeicons/core-free-icons/Upload01Icon';
import UserCheck01IconData from '@hugeicons/core-free-icons/UserCheck01Icon';
import UserCircleIconData from '@hugeicons/core-free-icons/UserCircleIcon';
import UserGroupIconData from '@hugeicons/core-free-icons/UserGroupIcon';
import UserIconData from '@hugeicons/core-free-icons/UserIcon';
import UserMultipleIconData from '@hugeicons/core-free-icons/UserMultipleIcon';
import UserRemove01IconData from '@hugeicons/core-free-icons/UserRemove01Icon';
import Video01IconData from '@hugeicons/core-free-icons/Video01Icon';
import Wallet01IconData from '@hugeicons/core-free-icons/Wallet01Icon';
import Wifi01IconData from '@hugeicons/core-free-icons/Wifi01Icon';
import Wrench01IconData from '@hugeicons/core-free-icons/Wrench01Icon';
import ZapIconData from '@hugeicons/core-free-icons/ZapIcon';
import ZoomInAreaIconData from '@hugeicons/core-free-icons/ZoomInAreaIcon';
import ZoomOutAreaIconData from '@hugeicons/core-free-icons/ZoomOutAreaIcon';

const createIcon = (icon, displayName) => {
  const Icon = forwardRef(({
    size = 24,
    color = 'currentColor',
    strokeWidth = 1.7,
    className,
    ...props
  }, ref) => (
    <HugeiconsIcon
      ref={ref}
      icon={icon}
      size={size}
      color={color}
      strokeWidth={strokeWidth}
      className={className}
      {...props}
    />
  ));

  Icon.displayName = displayName;
  return Icon;
};

export const Activity = createIcon(Activity01IconData, 'Activity');
export const AlertCircle = createIcon(AlertCircleIconData, 'AlertCircle');
export const AlertTriangle = createIcon(Alert01IconData, 'AlertTriangle');
export const Archive = createIcon(ArchiveIconData, 'Archive');
export const ArrowDownRight = createIcon(ArrowDownRight01IconData, 'ArrowDownRight');
export const ArrowLeft = createIcon(ArrowLeft01IconData, 'ArrowLeft');
export const ArrowRight = createIcon(ArrowRight01IconData, 'ArrowRight');
export const ArrowUpCircle = createIcon(CircleArrowUp01IconData, 'ArrowUpCircle');
export const ArrowUpRight = createIcon(ArrowUpRight01IconData, 'ArrowUpRight');
export const Award = createIcon(Award01IconData, 'Award');
export const BarChart2 = createIcon(BarChartIconData, 'BarChart2');
export const BarChart3 = createIcon(BarChartIconData, 'BarChart3');
export const Bell = createIcon(BellIconData, 'Bell');
export const Bold = createIcon(BoldIconData, 'Bold');
export const BookOpen = createIcon(BookOpen01IconData, 'BookOpen');
export const Bot = createIcon(BotIconData, 'Bot');
export const Brain = createIcon(BrainIconData, 'Brain');
export const Building2 = createIcon(Building02IconData, 'Building2');
export const Calendar = createIcon(Calendar01IconData, 'Calendar');
export const CalendarClock = createIcon(CalendarClockIconData, 'CalendarClock');
export const CalendarDays = createIcon(CalendarDaysIconData, 'CalendarDays');
export const Camera = createIcon(Camera01IconData, 'Camera');
export const Check = createIcon(CheckIconData, 'Check');
export const CheckCircle = createIcon(CheckmarkCircle01IconData, 'CheckCircle');
export const CheckCircle2 = createIcon(CheckmarkCircle02IconData, 'CheckCircle2');
export const CheckSquare = createIcon(CheckmarkSquare01IconData, 'CheckSquare');
export const ChevronDown = createIcon(ChevronDownIconData, 'ChevronDown');
export const ChevronLeft = createIcon(ChevronLeftIconData, 'ChevronLeft');
export const ChevronRight = createIcon(ChevronRightIconData, 'ChevronRight');
export const ChevronUp = createIcon(ChevronUpIconData, 'ChevronUp');
export const Circle = createIcon(CircleIconData, 'Circle');
export const CircleDot = createIcon(CircleDotIconData, 'CircleDot');
export const ClipboardList = createIcon(ClipboardListIconData, 'ClipboardList');
export const Clock = createIcon(Clock01IconData, 'Clock');
export const CloudUpload = createIcon(CloudUploadIconData, 'CloudUpload');
export const Coffee = createIcon(Coffee01IconData, 'Coffee');
export const Compass = createIcon(CompassIconData, 'Compass');
export const Copy = createIcon(CopyIconData, 'Copy');
export const Cpu = createIcon(CpuIconData, 'Cpu');
export const Database = createIcon(DatabaseIconData, 'Database');
export const DollarSign = createIcon(DollarSignIconData, 'DollarSign');
export const Download = createIcon(Download01IconData, 'Download');
export const Edit = createIcon(Edit01IconData, 'Edit');
export const Edit2 = createIcon(PencilEdit02IconData, 'Edit2');
export const Edit3 = createIcon(PencilEdit02IconData, 'Edit3');
export const ExternalLink = createIcon(ExternalLinkIconData, 'ExternalLink');
export const Eye = createIcon(EyeIconData, 'Eye');
export const Facebook = createIcon(Facebook01IconData, 'Facebook');
export const File = createIcon(File01IconData, 'File');
export const FileArchive = createIcon(FileArchiveIconData, 'FileArchive');
export const FileAudio = createIcon(FileAudioIconData, 'FileAudio');
export const FileBarChart = createIcon(FileChartColumnIconData, 'FileBarChart');
export const FileSpreadsheet = createIcon(FileSpreadsheetIconData, 'FileSpreadsheet');
export const FileText = createIcon(File02IconData, 'FileText');
export const FileVideo = createIcon(FileVideoIconData, 'FileVideo');
export const Filter = createIcon(FilterIconData, 'Filter');
export const Flame = createIcon(FlameIconData, 'Flame');
export const Folder = createIcon(Folder01IconData, 'Folder');
export const FolderOpen = createIcon(FolderOpenIconData, 'FolderOpen');
export const Globe = createIcon(GlobeIconData, 'Globe');
export const Grid = createIcon(GridIconData, 'Grid');
export const Hand = createIcon(HandIconData, 'Hand');
export const Heading1 = createIcon(Heading01IconData, 'Heading1');
export const Heading2 = createIcon(Heading02IconData, 'Heading2');
export const Heading3 = createIcon(Heading03IconData, 'Heading3');
export const HelpCircle = createIcon(HelpCircleIconData, 'HelpCircle');
export const Highlighter = createIcon(HighlighterIconData, 'Highlighter');
export const History = createIcon(HistoryIconData, 'History');
export const Image = createIcon(Image01IconData, 'Image');
export const ImageIcon = createIcon(Image01IconData, 'ImageIcon');
export const Info = createIcon(InformationCircleIconData, 'Info');
export const Instagram = createIcon(InstagramIconData, 'Instagram');
export const Italic = createIcon(TextItalicIconData, 'Italic');
export const Key = createIcon(Key01IconData, 'Key');
export const KeyRound = createIcon(Key02IconData, 'KeyRound');
export const Layers = createIcon(Layers01IconData, 'Layers');
export const Layout = createIcon(Layout01IconData, 'Layout');
export const LayoutDashboard = createIcon(DashboardSquare01IconData, 'LayoutDashboard');
export const LayoutGrid = createIcon(LayoutGridIconData, 'LayoutGrid');
export const Lightbulb = createIcon(BulbIconData, 'Lightbulb');
export const Link = createIcon(Link01IconData, 'Link');
export const Link2 = createIcon(Link02IconData, 'Link2');
export const List = createIcon(ListViewIconData, 'List');
export const ListCollapse = createIcon(HierarchyFilesIconData, 'ListCollapse');
export const ListOrdered = createIcon(LeftToRightListNumberIconData, 'ListOrdered');
export const ListTodo = createIcon(CheckListIconData, 'ListTodo');
export const Loader2 = createIcon(Loading03IconData, 'Loader2');
export const Lock = createIcon(LockIconData, 'Lock');
export const LockKeyhole = createIcon(LockKeyIconData, 'LockKeyhole');
export const LogOut = createIcon(Logout01IconData, 'LogOut');
export const Mail = createIcon(Mail01IconData, 'Mail');
export const Map = createIcon(MapsIconData, 'Map');
export const Maximize2 = createIcon(Maximize02IconData, 'Maximize2');
export const Megaphone = createIcon(Megaphone01IconData, 'Megaphone');
export const Menu = createIcon(Menu01IconData, 'Menu');
export const MessageCircle = createIcon(BubbleChatIconData, 'MessageCircle');
export const MessageSquare = createIcon(Message01IconData, 'MessageSquare');
export const MessageSquareText = createIcon(Message02IconData, 'MessageSquareText');
export const Mic = createIcon(Mic01IconData, 'Mic');
export const Minimize2 = createIcon(Minimize02IconData, 'Minimize2');
export const Monitor = createIcon(ComputerIconData, 'Monitor');
export const Moon = createIcon(MoonIconData, 'Moon');
export const MoreHorizontal = createIcon(MoreHorizontalIconData, 'MoreHorizontal');
export const MoreVertical = createIcon(MoreVerticalIconData, 'MoreVertical');
export const MousePointer2 = createIcon(Cursor02IconData, 'MousePointer2');
export const Music = createIcon(MusicNote01IconData, 'Music');
export const Palette = createIcon(ColorPickerIconData, 'Palette');
export const Paperclip = createIcon(AttachmentIconData, 'Paperclip');
export const Pencil = createIcon(PencilIconData, 'Pencil');
export const PieChart = createIcon(PieChartIconData, 'PieChart');
export const PlayCircle = createIcon(PlayCircleIconData, 'PlayCircle');
export const Plus = createIcon(Add01IconData, 'Plus');
export const PlusCircle = createIcon(AddCircleIconData, 'PlusCircle');
export const Presentation = createIcon(Presentation01IconData, 'Presentation');
export const QrCode = createIcon(QrCodeIconData, 'QrCode');
export const Radar = createIcon(Radar01IconData, 'Radar');
export const RefreshCcw = createIcon(RefreshIconData, 'RefreshCcw');
export const RefreshCw = createIcon(RefreshIconData, 'RefreshCw');
export const RotateCcw = createIcon(RotateLeft01IconData, 'RotateCcw');
export const TaskReturnIcon = createIcon(RefreshIconData, 'TaskReturnIcon');
export const TaskReintegrateIcon = createIcon(RedoIconData, 'TaskReintegrateIcon');
export const Save = createIcon(SaveIconData, 'Save');
export const Search = createIcon(Search01IconData, 'Search');
export const Send = createIcon(MailSend01IconData, 'Send');
export const Settings = createIcon(Settings01IconData, 'Settings');
export const Settings2 = createIcon(Settings02IconData, 'Settings2');
export const Share2 = createIcon(Share02IconData, 'Share2');
export const ShieldCheck = createIcon(SecurityCheckIconData, 'ShieldCheck');
export const Smartphone = createIcon(SmartPhone01IconData, 'Smartphone');
export const Sparkles = createIcon(SparklesIconData, 'Sparkles');
export const Star = createIcon(StarIconData, 'Star');
export const StickyNote = createIcon(StickyNote01IconData, 'StickyNote');
export const StopCircle = createIcon(StopCircleIconData, 'StopCircle');
export const Sun = createIcon(Sun01IconData, 'Sun');
export const Table2 = createIcon(Table01IconData, 'Table2');
export const Tag = createIcon(Tag01IconData, 'Tag');
export const Target = createIcon(Target01IconData, 'Target');
export const Thermometer = createIcon(ThermometerIconData, 'Thermometer');
export const Trash2 = createIcon(Delete02IconData, 'Trash2');
export const TrendingDown = createIcon(AnalyticsDownIconData, 'TrendingDown');
export const TrendingUp = createIcon(AnalyticsUpIconData, 'TrendingUp');
export const Trophy = createIcon(ChampionIconData, 'Trophy');
export const Type = createIcon(TextIconData, 'Type');
export const Underline = createIcon(TextUnderlineIconData, 'Underline');
export const Upload = createIcon(Upload01IconData, 'Upload');
export const UploadCloud = createIcon(CloudUploadIconData, 'UploadCloud');
export const User = createIcon(UserIconData, 'User');
export const UserCheck = createIcon(UserCheck01IconData, 'UserCheck');
export const UserRound = createIcon(UserCircleIconData, 'UserRound');
export const UserX = createIcon(UserRemove01IconData, 'UserX');
export const Users = createIcon(UserMultipleIconData, 'Users');
export const UsersRound = createIcon(UserGroupIconData, 'UsersRound');
export const Video = createIcon(Video01IconData, 'Video');
export const Wallet = createIcon(Wallet01IconData, 'Wallet');
export const Wifi = createIcon(Wifi01IconData, 'Wifi');
export const Wrench = createIcon(Wrench01IconData, 'Wrench');
export const X = createIcon(Cancel01IconData, 'X');
export const Zap = createIcon(ZapIconData, 'Zap');
export const ZoomIn = createIcon(ZoomInAreaIconData, 'ZoomIn');
export const ZoomOut = createIcon(ZoomOutAreaIconData, 'ZoomOut');
